### ISSUE TITLE
如果像SVProgressHUD 类方法就好了

### ISSUE THREAD

**Issue by XavierLost** [Abnerzj/ZJAnimationPopView#1]

**Comment by Abnerzj** [comment]
感谢你的建议! 之前也考虑过用类方法来调用，类方法在实例化的时候只需要调用一个方法，用起来直观感觉爽一些，但是用类方法就意味着开辟了一块一直占据者内存的单例对象，而弹框不是在应用中每个场合经常使用到，用完即可释放。其次，考虑到弹框还有很多属性可以自定义，用对象方法来设置这些属性参数比用类方法设置更加符合我们正常的开发习惯。当然，如果你的应用使用弹框很频繁，使用类方法来调用是完全Nice的，可以避免频繁开辟内存的操作。你只需要扩展一个单例方法，通过单例对象去初始化和设置属性就行咯，需要注意的是，在下次pop时把属性重置哦。
