### ISSUE TITLE
希望能够通过view弹出弹框

### ISSUE THREAD

**Issue by liqiantu** [Abnerzj/ZJAnimationPopView#5]
感谢提供这么好用的弹窗。
现在弹窗默认是加载到keyWindow上的，使用过程中发现两个问题。
1.弹窗不关闭，push到下个控制器，弹窗会覆盖到下一页上。
2.弹窗不关闭，prsent alterController，弹窗会覆盖alert上。
我改成这样，就正常了。

- (void)pop
{
    if (self.fromView) {
        [self.fromView addSubview:self];
    }else {
        [[UIApplication sharedApplication].keyWindow addSubview:self];
    }
    
    __weak typeof(self) ws = self;

**Comment by Abnerzj** [comment]
如果不需要弹框，在进入下一个页面之前可以调用-dismiss方法关闭弹框。如果要弹框在上一个页面不关闭，按照你这种方式是可以做到的。
